server:
  port: 8181

mongodb:
  host: mongodb://mongo
  name: things_db

things:
  host: things
  port: 8182

rabbitmq:
  url: amqp://knot:knot@rabbitmq

logger:
  level: debug

expiration:
  time: 604800